aliases:
    fleeks: cd ~/.local/share/fleek
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
allow_broken: false
auto_gc: true
bling: high
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: aarch64
      home: ""
      hostname: NWL-STUDIO.local
      os: darwin
      user:
        email: nigel.williamslucas@gmail.com
        name: Nigel Williams-Lucas
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: nwilliams-lucas
      username: nwilliams-lucas
    - arch: aarch64
      home: ""
      hostname: NWL-MBM2
      os: darwin
      user:
        email: nigel.williamslucas@gmail.com
        name: Nigel Williams-Lucas
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: nwilliams-lucas
      username: nwilliams-lucas
track: nixos-unstable
unfree: true
users: []
